services:
  # BACKEND
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 9000:9000
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql_db
    networks:
      app:
        aliases:
          - backend
        

  # FRONTEND

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    links:
      - backend
    networks:
      - app

  # Nginx

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - backend
    links:
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app
  
  # MySQL server
  mysql_db:
    image: mysql:8.2
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: newswire
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
    ports:
      - 9001:80
    networks:
      - app
volumes:
  dbdata:
networks:
  app:
    driver: bridge
