version: "4.25.2"
services:
  #######################################
  # BACKEND
  #######################################

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql_db
    networks:
      - default
  #######################################
  # FRONTEND
  #######################################

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./frontend:/frontend
  #   depends_on:
  #     - backend
  #   networks:
  #     - default
  #######################################
  # MySQL server
  #######################################

  mysql_db:
    image: mysql:8.2
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: newswire
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - default
  #######################################
  # PhpMyAdmin
  #######################################

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
    ports:
      - 9001:80
    networks:
      - default
volumes:
  dbdata:
