version: "4.25.2"
services:
  # Backend

  backend:
    container_name: backend
    build:
      context: ./backend
      target: php
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql_db
    networks:
      app:
        aliases:
          - backend

  # Frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - app

  # MySQL server

  mysql_db:
    image: mysql:8.2
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: newswire
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app

  # PhpMyAdmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
    ports:
      - 9001:80
    networks:
      - app

volumes:
  dbdata: ~
networks:
  app:
    driver: bridge
