export default {
  TOGGLE_THEME: "TOGGLE_THEME",
  // Auth:
  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
  LOGOUT_USER: "LOGOUT_USER",

  SIGNUP_USER: "SIGNUP_USER",
  SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
  SIGNUP_USER_ERROR: "SIGNUP_USER_ERROR",

  USER_PROFILE: 'USER_PROFILE',
  USER_PROFILE_SUCCESS: 'USER_PROFILE_SUCCESS',
  USER_PROFILE_ERROR: 'USER_PROFILE_ERROR',
};
