export default {
    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_ERROR: 'GET_CATEGORIES_ERROR',

    GET_SOURCES: 'GET_SOURCES',
    GET_SOURCES_SUCCESS: 'GET_SOURCES_SUCCESS',
    GET_SOURCES_ERROR: 'GET_SOURCES_ERROR',

    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    UPDATE_SETTINGS_SUCCESS: 'UPDATE_SETTINGS_SUCCESS',
    UPDATE_SETTINGS_ERROR: 'UPDATE_SETTINGS_ERROR',
}