export default {
    GET_NEWS: 'GET_NEWS',
    GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
    GET_NEWS_ERROR: 'GET_NEWS_ERROR',

    GET_ARTICLE: 'GET_ARTICLE',
    GET_ARTICLE_SUCCESS: 'GET_ARTICLE_SUCCESS',
    GET_ARTICLE_ERROR: 'GET_ARTICLE_ERROR',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_ERROR: 'GET_CATEGORIES_ERROR',

    GET_SOURCES: 'GET_SOURCES',
    GET_SOURCES_SUCCESS: 'GET_SOURCES_SUCCESS',
    GET_SOURCES_ERROR: 'GET_SOURCES_ERROR',
}